@extends('layouts.lafac-store')
@section('main')
    @include('livewire.lafacstore.nav-bar')
    @include('livewire.lafacstore.header')
    @include('livewire.lafacstore.products')
    @include('livewire.lafacstore.categories')
    @include('livewire.lafacstore.cart')
    @include('livewire.lafacstore.footer')
@endsection
